apiVersion: v1 
kind: Service
metadata:
  name: my-service
  labels:
    name: result-app
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app