apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set
  labels:
    app: my-app
    type: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
        type: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80