apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc-demo
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: my-rc-container
        image: nginx
        ports:
        - containerPort: 80
