apiVersion: v1 
kind: Pod
metadata:
  name:  my-pod
  labels:
    app: multi-pod
    type: init-pod
spec:
  containers:
  - name: nginx
    image:  nginx:latest
    ports:
    - containerPort: 80
  - name: busybox 
    image: busybox:latest
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']