apiVersion: v1
kind: Pod
metadata:
  name: multi-container-example
  labels:
    app: web-app
spec:
  # Init container to run database migration
  initContainers:
  - name: init-db
    image: busybox
    command:  ['sh', '-c', 'echo "Initializing database..." && sleep 5']
  
  # Main Application container
  containers:
  - name: web-app
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi 
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3

  - name: log-sidecar
    image: busybox
    command: ['sh', '-c', 'tail -n+1 -f /var/log/nginx/access.log']
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  
  # volumes share between containers
  volumes:
    - name: shared-logs
      emptyDir: {}