apiVersion: v1 
kind: Pod 
metadata:
  name: my-pod
  labels:
    app: my-app
    type: frontend
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
  nodeSelector: 
    size: Larger
  resources:
    requests: #  Requested resources
      memory: 1Gi # 256M 
      cpu: 1  # 0.1 = 100m ,millicores # 1 = 1Vcpu
    limits: 
      memory: 2Gi 
      cpu: 2  